# Generated by Django 6.0.8 on 2026-09-27 10:25

import apps.common.storage
import apps.contracts.models
import apps.contracts.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_alter_schoolsettings_brand_color"),
        ("people", "0002_passport_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="raqami",
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        blank=True,
                        help_text="Shartnoma tuzilgan paytdagi sinf (keyin o'zgarsa ham saqlanadi)",
                        max_length=40,
                        verbose_name="sinf",
                    ),
                ),
                (
                    "full_tariff",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1"))
                        ],
                        verbose_name="to'liq tarif (oyiga)",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="chegirma (%)",
                    ),
                ),
                (
                    "discount_reason",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="chegirma sababi"
                    ),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        verbose_name="oylik to'lov",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="boshlanish sanasi")),
                ("end_date", models.DateField(verbose_name="tugash sanasi")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("sent", "Yuborilgan"),
                            ("signed", "Imzolangan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                        verbose_name="holati",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="yuborilgan"
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="imzolangan"
                    ),
                ),
                (
                    "signed_phone",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="tasdiqlagan telefon"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="bekor qilingan"
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="bekor qilish sababi"
                    ),
                ),
                (
                    "scan",
                    models.FileField(
                        blank=True,
                        storage=apps.common.storage.PrivateStorage(),
                        upload_to=apps.contracts.models.scan_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"]),
                            apps.contracts.validators.validate_pdf,
                        ],
                        verbose_name="skaner (PDF)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="izoh")),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="core.academicyear",
                        verbose_name="o'quv yili",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="core.branch",
                        verbose_name="filial",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="tuzgan xodim",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="people.guardian",
                        verbose_name="shartnoma tomoni (ota-ona)",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="people.student",
                        verbose_name="o'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "shartnoma",
                "verbose_name_plural": "shartnomalar",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["branch", "status"],
                        name="contracts_c_branch__c797f9_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "cancelled"), _negated=True),
                        fields=("student", "academic_year"),
                        name="one_active_contract_per_student_year",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gt", models.F("start_date"))),
                        name="contract_dates_order",
                    ),
                ],
            },
        ),
    ]
