# Generated by Django 6.0.8 on 2026-09-30 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="nomi"),
                ),
                ("body", models.TextField(verbose_name="matn")),
                ("is_active", models.BooleanField(default=True, verbose_name="faol")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="sukut bo'yicha"),
                ),
            ],
            options={
                "verbose_name": "shartnoma shabloni",
                "verbose_name_plural": "shartnoma shablonlari",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="signed_body",
            field=models.TextField(
                blank=True, editable=False, verbose_name="imzolangan matn"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="signed_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                editable=False,
                verbose_name="imzolangan ma'lumotlar",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="contracts.contracttemplate",
                verbose_name="shablon",
            ),
        ),
    ]
