# Generated by Django 6.0.8 on 2026-09-27 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimecode",
            name="channel",
            field=models.CharField(
                choices=[("sms", "SMS"), ("telegram", "Telegram")],
                default="sms",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="TelegramLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.BigIntegerField(unique=True, verbose_name="chat ID"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Telegram username"
                    ),
                ),
                (
                    "linked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ulangan"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram ulanishi",
                "verbose_name_plural": "Telegram ulanishlari",
            },
        ),
    ]
