# Generated by Django 6.0.8 on 2026-09-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_telegram_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimecode",
            name="subject",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Kod qaysi obyekt uchun, masalan: contract:15",
                max_length=40,
            ),
        ),
    ]
