# Generated by Django 6.0.8 on 2026-09-27 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_otp_subject"),
        ("core", "0003_alter_schoolsettings_brand_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpersonationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("role", "Rol sifatida ko'rish"),
                            ("user", "Foydalanuvchi sifatida kirish"),
                        ],
                        max_length=10,
                        verbose_name="rejim",
                    ),
                ),
                (
                    "role",
                    models.CharField(blank=True, max_length=20, verbose_name="rol"),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="boshlangan"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="tugagan"),
                ),
                (
                    "actions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="o'zgartirish so'rovlari"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impersonations_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="superadmin",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.branch",
                        verbose_name="filial",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impersonations_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="kim sifatida",
                    ),
                ),
            ],
            options={
                "verbose_name": "impersonation jurnali",
                "verbose_name_plural": "impersonation jurnali",
                "ordering": ["-started_at"],
            },
        ),
    ]
