# Generated by Django 6.0.8 on 2026-10-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_impersonation_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("teacher", "O'qituvchi"),
                    ("head_teacher", "Zavuch"),
                    ("reception", "Qabul | Reception"),
                    ("director", "Direktor"),
                ],
                max_length=20,
                verbose_name="rol",
            ),
        ),
    ]
