# Generated by Django 6.0.8 on 2026-09-27 06:58

import apps.common.fields
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("core", "0003_alter_schoolsettings_brand_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                ("last_name", models.CharField(max_length=60, verbose_name="familiya")),
                ("first_name", models.CharField(max_length=60, verbose_name="ism")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="otasining ismi"
                    ),
                ),
                (
                    "passport",
                    apps.common.fields.EncryptedCharField(
                        blank=True,
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}\\d{7}$",
                                "Passport: 2 ta lotin harf va 7 ta raqam (AB1234567).",
                            )
                        ],
                        verbose_name="passport",
                    ),
                ),
                (
                    "pinfl",
                    apps.common.fields.EncryptedCharField(
                        blank=True,
                        max_length=14,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{14}$", "JSHSHIR 14 ta raqamdan iborat."
                            )
                        ],
                        verbose_name="JSHSHIR",
                    ),
                ),
                (
                    "pinfl_index",
                    models.CharField(
                        blank=True, db_index=True, editable=False, max_length=64
                    ),
                ),
                ("phone", models.CharField(max_length=12, verbose_name="telefon")),
                (
                    "extra_phone",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="qo'shimcha telefon"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="manzil"),
                ),
                (
                    "workplace",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="ish joyi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Faol"), ("inactive", "Nofaol")],
                        default="active",
                        max_length=10,
                        verbose_name="holati",
                    ),
                ),
            ],
            options={
                "verbose_name": "ota-ona / vasiy",
                "verbose_name_plural": "ota-onalar",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                ("last_name", models.CharField(max_length=60, verbose_name="familiya")),
                ("first_name", models.CharField(max_length=60, verbose_name="ism")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="otasining ismi"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False, max_length=20, unique=True, verbose_name="kodi"
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="tug'ilgan sana")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "O'g'il"), ("F", "Qiz")],
                        max_length=1,
                        verbose_name="jinsi",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=12, verbose_name="telefon"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="manzil"),
                ),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(11),
                        ],
                        verbose_name="sinf (daraja)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Faol"),
                            ("frozen", "Muzlatilgan"),
                            ("left", "Ketgan"),
                            ("graduated", "Bitirgan"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                        verbose_name="holati",
                    ),
                ),
                (
                    "in_erp",
                    models.BooleanField(
                        default=False, verbose_name="ERP'ga kiritilgan"
                    ),
                ),
                (
                    "in_emaktab",
                    models.BooleanField(
                        default=False, verbose_name="E-maktab'ga kiritilgan"
                    ),
                ),
                ("joined_at", models.DateField(verbose_name="qabul qilingan")),
                (
                    "left_at",
                    models.DateField(blank=True, null=True, verbose_name="ketgan sana"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="izoh")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="core.branch",
                        verbose_name="filial",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="academics.schoolclass",
                        verbose_name="sinf / yo'nalish",
                    ),
                ),
            ],
            options={
                "verbose_name": "o'quvchi",
                "verbose_name_plural": "o'quvchilar",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentGuardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("father", "Ota"),
                            ("mother", "Ona"),
                            ("other", "Vasiy"),
                        ],
                        max_length=10,
                        verbose_name="munosabati",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Shartnoma va SMS'lar shu odamga yuboriladi",
                        verbose_name="asosiy aloqa",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_links",
                        to="people.guardian",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_links",
                        to="people.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "o'quvchi — ota-ona",
                "verbose_name_plural": "o'quvchi — ota-ona",
            },
        ),
        migrations.AddField(
            model_name="guardian",
            name="children",
            field=models.ManyToManyField(
                related_name="guardians",
                through="people.StudentGuardian",
                to="people.student",
                verbose_name="farzandlari",
            ),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "passport",
                    apps.common.fields.EncryptedCharField(
                        blank=True,
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}\\d{7}$",
                                "Passport: 2 ta lotin harf va 7 ta raqam (AB1234567).",
                            )
                        ],
                        verbose_name="passport",
                    ),
                ),
                (
                    "pinfl",
                    apps.common.fields.EncryptedCharField(
                        blank=True,
                        max_length=14,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{14}$", "JSHSHIR 14 ta raqamdan iborat."
                            )
                        ],
                        verbose_name="JSHSHIR",
                    ),
                ),
                (
                    "pinfl_index",
                    models.CharField(
                        blank=True, db_index=True, editable=False, max_length=64
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False, max_length=20, unique=True, verbose_name="kodi"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="tug'ilgan sana"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "O'g'il"), ("F", "Qiz")],
                        max_length=1,
                        verbose_name="jinsi",
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="manzil"),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Turmush qurmagan"),
                            ("married", "Turmush qurgan"),
                        ],
                        max_length=10,
                        verbose_name="oilaviy holati",
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("secondary", "O'rta"),
                            ("vocational", "O'rta maxsus"),
                            ("higher", "Oliy"),
                            ("master", "Magistr"),
                        ],
                        max_length=12,
                        verbose_name="ma'lumoti",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="mutaxassisligi"
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ish staji (yil)"
                    ),
                ),
                (
                    "category",
                    models.CharField(blank=True, max_length=40, verbose_name="toifasi"),
                ),
                (
                    "hired_at",
                    models.DateField(blank=True, null=True, verbose_name="ishga qabul"),
                ),
                (
                    "contract_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="shartnoma boshlanishi"
                    ),
                ),
                (
                    "contract_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="shartnoma tugashi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Faol"),
                            ("vacation", "Ta'tilda"),
                            ("dismissed", "Bo'shatilgan"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                        verbose_name="holati",
                    ),
                ),
                (
                    "teaching_languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[("uz", "O'zbek"), ("ru", "Rus"), ("en", "Ingliz")],
                            max_length=2,
                        ),
                        blank=True,
                        default=list,
                        verbose_name="o'qitish tillari",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teachers",
                        to="core.branch",
                        verbose_name="filial",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teachers",
                        to="academics.subject",
                        verbose_name="o'qitish fanlari",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teacher",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "o'qituvchi",
                "verbose_name_plural": "o'qituvchilar",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["branch", "status"], name="people_stud_branch__4c4b20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                django.db.models.functions.text.Upper("last_name"),
                name="student_last_name_upper",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentguardian",
            constraint=models.UniqueConstraint(
                fields=("student", "guardian"), name="unique_student_guardian"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentguardian",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("student",),
                name="one_primary_guardian_per_student",
            ),
        ),
        migrations.AddIndex(
            model_name="guardian",
            index=models.Index(fields=["phone"], name="people_guar_phone_a849f0_idx"),
        ),
    ]
