# Generated by Django 6.0.8 on 2026-09-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="passport_index",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=64
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="passport_index",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=64
            ),
        ),
    ]
