# Generated by Django 6.0.8 on 2026-09-27 15:30

import apps.common.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_passport_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="birth_certificate",
            field=apps.common.fields.EncryptedCharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z0-9-]{5,20}$",
                        "Guvohnoma raqami: lotin harflari, raqam va chiziqcha (I-FR-1234567).",
                    )
                ],
                verbose_name="tug'ilganlik guvohnomasi",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="district",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="tuman / shahar"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mahalla",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="mahalla / qishloq"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="passport",
            field=apps.common.fields.EncryptedCharField(
                blank=True,
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{2}\\d{7}$",
                        "Passport: 2 ta lotin harf va 7 ta raqam (AB1234567).",
                    )
                ],
                verbose_name="passport",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="passport_index",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=64
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="pinfl",
            field=apps.common.fields.EncryptedCharField(
                blank=True,
                max_length=14,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{14}$", "JSHSHIR 14 ta raqamdan iborat."
                    )
                ],
                verbose_name="JSHSHIR",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="pinfl_index",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=64
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="region",
            field=models.CharField(blank=True, max_length=80, verbose_name="viloyat"),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ko'cha / uy"
            ),
        ),
    ]
