# Generated by Django 6.0.8 on 2026-09-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_student_documents_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="position",
            field=models.CharField(blank=True, max_length=120, verbose_name="lavozimi"),
        ),
    ]
