# Generated by Django 6.0.8 on 2026-09-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_guardian_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentguardian",
            name="relation",
            field=models.CharField(
                choices=[
                    ("father", "Ota"),
                    ("mother", "Ona"),
                    ("grandpa", "Buva"),
                    ("grandma", "Buvi"),
                    ("uncle", "Tog'a"),
                    ("aunt", "Xola"),
                    ("other", "Boshqa"),
                ],
                max_length=10,
                verbose_name="munosabati",
            ),
        ),
    ]
