# Generated by Django 6.0.8 on 2026-09-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_more_relations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Faol"),
                    ("inactive", "Nofaol"),
                    ("graduated", "Bitirgan"),
                    ("expelled", "O'qishdan chiqarilgan"),
                    ("frozen", "Ta'tilda"),
                    ("left", "Ketgan"),
                ],
                db_index=True,
                default="active",
                max_length=10,
                verbose_name="holati",
            ),
        ),
    ]
