# Generated by Django 6.0.8 on 2026-09-29 17:52

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0006_student_statuses"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        db_index=True, max_length=80, verbose_name="viloyat"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, verbose_name="tuman / shahar"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="faol")),
            ],
            options={
                "verbose_name": "tuman / shahar",
                "verbose_name_plural": "tumanlar / shaharlar",
                "ordering": ["region", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("region", "name"), name="unique_district_per_region"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Mahalla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="mahalla / qishloq"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mahallas",
                        to="people.district",
                        verbose_name="tuman / shahar",
                    ),
                ),
            ],
            options={
                "verbose_name": "mahalla",
                "verbose_name_plural": "mahallalar",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Upper("name"),
                        models.F("district"),
                        name="unique_mahalla_per_district",
                    )
                ],
            },
        ),
    ]
