# Generated by Django 6.0.8 on 2026-10-02 02:59

from django.db import migrations, models


def map_categories(apps, schema_editor):
    """Erkin matndagi toifani ro'yxat qiymatiga: "Oliy toifa" → highest, "1 - TOIFA" → first va h.k.
    Tanib bo'lmagani bo'sh qoldiriladi (ustun qisqarguncha bajariladi)."""
    Teacher = apps.get_model("people", "Teacher")
    for t in Teacher.objects.exclude(category=""):
        raw = t.category.lower()
        value = ("highest" if "oliy" in raw else "specialist" if "mutaxassis" in raw
                 else "first" if "1" in raw else "second" if "2" in raw else "")
        Teacher.objects.filter(pk=t.pk).update(category=value)


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0008_seed_districts"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="kind",
            field=models.CharField(
                choices=[
                    ("teacher", "O'qituvchi"),
                    ("coordinator", "Koordinator"),
                    ("assistant", "Yordamchi o'qituvchi"),
                ],
                db_index=True,
                default="teacher",
                max_length=12,
                verbose_name="turi",
            ),
        ),
        migrations.RunPython(map_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="teacher",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first", "1-toifa"),
                    ("second", "2-toifa"),
                    ("specialist", "Mutaxassis"),
                    ("highest", "Oliy toifa"),
                ],
                max_length=12,
                verbose_name="toifasi",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Faol"),
                    ("inactive", "Nofaol"),
                    ("vacation", "Ta'tilda"),
                    ("dismissed", "Bo'shatilgan"),
                ],
                db_index=True,
                default="active",
                max_length=10,
                verbose_name="holati",
            ),
        ),
    ]
