# Generated by Django 6.0.8 on 2026-10-02 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_hours_and_breaks"),
        ("people", "0009_teacher_kind_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="email"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="fixed_salary",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Darsbay/o'quvchibay hisobdan tashqari qat'iy oylik. 0 — yo'q",
                max_digits=12,
                verbose_name="belgilangan oylik (so'm)",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="notes",
            field=models.TextField(blank=True, verbose_name="izoh"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="official_employment",
            field=models.BooleanField(
                default=False, verbose_name="ish staji yoziladi (mehnat daftarchasi)"
            ),
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("national", "Milliy sertifikat"),
                            ("ielts", "IELTS"),
                            ("cefr", "CEFR"),
                            ("toefl", "TOEFL"),
                            ("other", "Boshqa"),
                        ],
                        max_length=10,
                        verbose_name="sertifikat turi",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        verbose_name="sertifikat raqami / darajasi",
                    ),
                ),
                ("issued_on", models.DateField(verbose_name="boshlanish sanasi")),
                ("expires_on", models.DateField(verbose_name="tugash sanasi")),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="ball",
                    ),
                ),
                (
                    "issued_by",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="kim tomonidan berilgan",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academics.subject",
                        verbose_name="fan",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="people.teacher",
                        verbose_name="o'qituvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "sertifikat",
                "verbose_name_plural": "sertifikatlar",
                "ordering": ["-expires_on"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("expires_on__gte", models.F("issued_on"))),
                        name="certificate_dates_order",
                    )
                ],
            },
        ),
    ]
