# Generated by Django 6.0.8 on 2026-10-02 03:43

import apps.common.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0010_teacher_hr_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="card_number",
            field=apps.common.fields.EncryptedCharField(
                blank=True,
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{16}$", "Karta raqami 16 ta raqam."
                    )
                ],
                verbose_name="karta raqami (oylik uchun)",
            ),
        ),
    ]
