# Generated by Django 6.0.8 on 2026-09-27 11:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        ("core", "0003_alter_schoolsettings_brand_color"),
        ("people", "0002_passport_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("fixed", "Doimiy (oy sayin bir xil limit)"),
                            ("normative", "Normativ (o'zgaruvchan limit)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("icon", models.CharField(default="receipt", max_length=20)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "xarajat kategoriyasi",
                "verbose_name_plural": "xarajat kategoriyalari",
                "ordering": ["kind", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cash", "Naqd kassa"),
                            ("bank", "Bank hisobi"),
                            ("terminal", "Terminal (karta)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "hisob",
                "verbose_name_plural": "hisoblar",
            },
        ),
        migrations.CreateModel(
            name="CashSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="boshlang'ich qoldiq",
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expected_cash",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="kutilgan naqd",
                    ),
                ),
                (
                    "counted_cash",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="sanalgan naqd",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_sessions",
                        to="core.branch",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "kassa sessiyasi",
                "verbose_name_plural": "kassa sessiyalari",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="summa",
                    ),
                ),
                ("spent_at", models.DateField(verbose_name="sana")),
                ("description", models.CharField(max_length=255, verbose_name="izoh")),
                ("is_reversed", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="finance.account",
                        verbose_name="hisob",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="core.branch",
                    ),
                ),
                (
                    "cash_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="finance.cashsession",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="finance.expensecategory",
                        verbose_name="kategoriya",
                    ),
                ),
            ],
            options={
                "verbose_name": "xarajat",
                "verbose_name_plural": "xarajatlar",
                "ordering": ["-spent_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BudgetLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(help_text="Oyning 1-sanasi")),
                (
                    "limit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="limit",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_limits",
                        to="core.branch",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="limits",
                        to="finance.expensecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "byudjet limiti",
                "verbose_name_plural": "byudjet limitlari",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tuition", "O'qish to'lovi"),
                            ("dorm", "Yotoqxona to'lovi"),
                        ],
                        default="tuition",
                        max_length=10,
                        verbose_name="turi",
                    ),
                ),
                (
                    "month",
                    models.DateField(help_text="Oyning 1-sanasi", verbose_name="oy"),
                ),
                (
                    "full_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Chegirmasiz, to'liq oy uchun",
                        max_digits=14,
                        verbose_name="to'liq tarif",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="chegirma",
                    ),
                ),
                (
                    "waived",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Oy o'rtasida kelgani uchun hisoblanmagan qism va boshqa kechishlar",
                        max_digits=14,
                        verbose_name="kechilgan",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="to'lanishi kerak"
                    ),
                ),
                (
                    "paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="to'langan",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="to'lov muddati")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("partial", "Qisman"),
                            ("paid", "To'langan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="holati",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="core.branch",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="contracts.contract",
                        verbose_name="shartnoma",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="people.student",
                        verbose_name="o'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "to'lov grafigi",
                "verbose_name_plural": "to'lov grafiklari",
                "ordering": ["month", "student__last_name"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="kvitansiya",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tuition", "O'qish to'lovi"),
                            ("dorm", "Yotoqxona to'lovi"),
                        ],
                        default="tuition",
                        max_length=10,
                        verbose_name="turi",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="summa",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Naqd"),
                            ("card", "Karta (terminal)"),
                            ("transfer", "Bank o'tkazmasi"),
                        ],
                        max_length=10,
                        verbose_name="to'lov usuli",
                    ),
                ),
                (
                    "card_network",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("humo", "Humo"),
                            ("uzcard", "Uzcard"),
                            ("visa", "Visa"),
                            ("other", "Boshqa"),
                        ],
                        max_length=10,
                        verbose_name="karta turi",
                    ),
                ),
                ("paid_at", models.DateTimeField(verbose_name="to'langan vaqt")),
                (
                    "payer_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="to'lovchi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Qabul qilingan"),
                            ("reversed", "Storno qilingan"),
                        ],
                        db_index=True,
                        default="ok",
                        max_length=10,
                        verbose_name="holati",
                    ),
                ),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("reverse_reason", models.CharField(blank=True, max_length=255)),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="izoh"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.account",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="core.branch",
                    ),
                ),
                (
                    "cash_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.cashsession",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="qabul qilgan",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="people.student",
                        verbose_name="o'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "to'lov",
                "verbose_name_plural": "to'lovlar",
                "ordering": ["-paid_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="finance.invoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="finance.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "to'lov taqsimoti",
                "verbose_name_plural": "to'lov taqsimotlari",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Kirim"), ("out", "Chiqim")], max_length=3
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("payment", "O'quvchi to'lovi"),
                            ("expense", "Xarajat"),
                            ("storno", "Storno"),
                            ("transfer", "Ichki o'tkazma"),
                            ("adjustment", "Kassa tafovuti"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Bank/terminal komissiyasi",
                        max_digits=14,
                    ),
                ),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="finance.account",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="core.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="finance.expense",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="finance.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "tranzaksiya",
                "verbose_name_plural": "tranzaksiyalar",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("branch", "kind"), name="one_account_kind_per_branch"
            ),
        ),
        migrations.AddConstraint(
            model_name="cashsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("closed_at__isnull", True)),
                fields=("branch",),
                name="one_open_cash_session_per_branch",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["branch", "spent_at"], name="finance_exp_branch__994a50_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetlimit",
            constraint=models.UniqueConstraint(
                fields=("branch", "category", "month"), name="one_limit_per_month"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["branch", "month", "status"],
                name="finance_inv_branch__a788d2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "cancelled"), _negated=True),
                fields=("student", "category", "month"),
                name="one_invoice_per_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("paid__gte", 0), ("paid__lte", models.F("amount"))),
                name="invoice_paid_within_amount",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["branch", "paid_at"], name="finance_pay_branch__abb871_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["branch", "occurred_at"], name="finance_tra_branch__5c7e5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["account", "direction"], name="finance_tra_account_253432_idx"
            ),
        ),
    ]
