# Generated by Django 6.0.8 on 2026-09-27 16:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_schoolsettings_brand_color"),
        ("finance", "0001_initial"),
        ("people", "0004_guardian_position"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("payment", "O'quvchi to'lovi"),
                    ("expense", "Xarajat"),
                    ("storno", "Storno"),
                    ("transfer", "Ichki o'tkazma"),
                    ("adjustment", "Kassa tafovuti"),
                    ("refund", "Qaytarilgan to'lov"),
                ],
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="raqami",
                    ),
                ),
                ("left_on", models.DateField(verbose_name="o'qishdan chiqqan sana")),
                (
                    "dorm_left_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="yotoqxonadan chiqqan sana"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("transfer", "Boshqa maktabga ko'chdi"),
                            ("relocation", "Yashash joyini o'zgartirdi"),
                            ("dropout", "O'qishni tashladi"),
                            ("financial", "To'lov qila olmaydi"),
                            ("expelled", "Maktab tomonidan chetlatildi"),
                            ("other", "Boshqa"),
                        ],
                        max_length=12,
                        verbose_name="sababi",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="izoh"),
                ),
                (
                    "charged",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="hisoblangan (jami)",
                    ),
                ),
                (
                    "paid",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="to'langan (jami)"
                    ),
                ),
                (
                    "refund",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="qaytarilgan",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="qolgan qarz",
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Naqd (kassadan)"),
                            ("transfer", "Bank o'tkazmasi"),
                        ],
                        max_length=10,
                        verbose_name="qaytarish usuli",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="finance.account",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawals",
                        to="core.branch",
                    ),
                ),
                (
                    "cash_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="finance.cashsession",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="rasmiylashtirgan",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawal",
                        to="people.student",
                        verbose_name="o'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "o'qishdan chiqish",
                "verbose_name_plural": "o'qishdan chiqishlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="withdrawal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="finance.withdrawal",
            ),
        ),
        migrations.CreateModel(
            name="WithdrawalLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("new_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("old_paid", models.DecimalField(decimal_places=2, max_digits=14)),
                ("new_paid", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="finance.invoice",
                    ),
                ),
                (
                    "withdrawal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="finance.withdrawal",
                    ),
                ),
            ],
            options={
                "verbose_name": "chiqish qatori",
                "verbose_name_plural": "chiqish qatorlari",
            },
        ),
    ]
