# Generated by Django 6.0.8 on 2026-09-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_withdrawal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="card_network",
            field=models.CharField(
                blank=True,
                choices=[
                    ("humo", "Humo"),
                    ("mastercard", "Mastercard"),
                    ("uzcard", "Uzcard"),
                    ("visa", "Visa"),
                    ("other", "Boshqa"),
                ],
                max_length=10,
                verbose_name="karta turi",
            ),
        ),
    ]
