# Generated by Django 6.0.8 on 2026-09-29 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dorm", "0003_stay_monthly_fee"),
        ("finance", "0003_mastercard"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="dorm_stay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="dorm.dormstay",
                verbose_name="yotoqxona qaydi",
            ),
        ),
    ]
