# Generated by Django 6.0.8 on 2026-09-27 06:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_alter_schoolsettings_brand_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "guruh fani",
                "verbose_name_plural": "guruh fanlari",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Masalan: 31-xona", max_length=40, verbose_name="nomi"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="sig'imi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="faol")),
            ],
            options={
                "verbose_name": "xona",
                "verbose_name_plural": "xonalar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                ("name", models.CharField(max_length=40, verbose_name="nomi")),
                (
                    "kind",
                    models.CharField(
                        choices=[("regular", "Oddiy sinf"), ("direction", "Yo'nalish")],
                        default="regular",
                        max_length=10,
                        verbose_name="turi",
                    ),
                ),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Yo'nalishlar uchun bo'sh qoldiriladi",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(11),
                        ],
                        verbose_name="sinf (daraja)",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("uz", "O'zbek"), ("ru", "Rus"), ("en", "Ingliz")],
                        default="uz",
                        max_length=2,
                        verbose_name="ta'lim tili",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="sig'imi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="faol")),
            ],
            options={
                "verbose_name": "sinf",
                "verbose_name_plural": "sinflar",
                "ordering": ["grade", "name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nomi")),
                (
                    "language",
                    models.CharField(
                        choices=[("uz", "O'zbek"), ("ru", "Rus"), ("en", "Ingliz")],
                        default="uz",
                        max_length=2,
                        verbose_name="o'qitish tili",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="faol")),
            ],
            options={
                "verbose_name": "fan",
                "verbose_name_plural": "fanlar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Masalan: IT+PHYS-Aniq1-01",
                        max_length=60,
                        verbose_name="kodi",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("whole_class", "Butun sinf"),
                            ("subset", "Tanlov guruhi"),
                        ],
                        default="whole_class",
                        max_length=12,
                        verbose_name="turi",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        help_text="Masalan: 2-darajali fanlarga",
                        max_length=60,
                        verbose_name="daraja",
                    ),
                ),
                (
                    "pay_scheme",
                    models.CharField(
                        choices=[
                            ("per_lesson", "Darsbay (dars × stavka)"),
                            ("per_student", "Belgilangan summa (o'quvchi boshiga)"),
                        ],
                        default="per_lesson",
                        max_length=12,
                        verbose_name="to'lov sxemasi",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2400"),
                        help_text="Darsbay: 1 dars uchun. O'quvchibay: 1 o'quvchi uchun oyiga",
                        max_digits=12,
                        verbose_name="stavka (so'm)",
                    ),
                ),
                (
                    "deduction_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="ushlanma (%)",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="sig'imi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="faol")),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="core.academicyear",
                        verbose_name="o'quv yili",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="core.branch",
                        verbose_name="filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "guruh",
                "verbose_name_plural": "guruhlar",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateField(verbose_name="qo'shilgan")),
                (
                    "left_at",
                    models.DateField(blank=True, null=True, verbose_name="chiqqan"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="academics.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "guruh a'zoligi",
                "verbose_name_plural": "guruh a'zoliklari",
            },
        ),
    ]
