# Generated by Django 6.0.8 on 2026-09-27 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("core", "0003_alter_schoolsettings_brand_color"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembership",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="people.student",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="groups",
                through="academics.GroupMembership",
                to="people.student",
                verbose_name="o'quvchilar",
            ),
        ),
        migrations.AddField(
            model_name="groupsubject",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="academics.group",
                verbose_name="guruh",
            ),
        ),
        migrations.AddField(
            model_name="groupsubject",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group_subjects",
                to="people.teacher",
                verbose_name="o'qituvchi",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rooms",
                to="core.branch",
                verbose_name="filial",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.room",
                verbose_name="xona",
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="core.academicyear",
                verbose_name="o'quv yili",
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="core.branch",
                verbose_name="filial",
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="homeroom_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homeroom_classes",
                to="people.teacher",
                verbose_name="sinf rahbari",
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.room",
                verbose_name="xona",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="groups",
                to="academics.schoolclass",
                verbose_name="sinf",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("name", "language"), name="unique_subject_language"
            ),
        ),
        migrations.AddField(
            model_name="groupsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="academics.subject",
                verbose_name="fan",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.UniqueConstraint(
                fields=("group", "student"), name="unique_group_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("branch", "name"), name="unique_room_branch"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.UniqueConstraint(
                fields=("branch", "academic_year", "name"), name="unique_class_per_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("branch", "academic_year", "code"), name="unique_group_per_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupsubject",
            constraint=models.UniqueConstraint(
                fields=("group", "subject"), name="unique_group_subject"
            ),
        ),
    ]
