# Generated by Django 6.0.8 on 2026-09-27 10:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclass",
            name="monthly_tariff",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1750000"),
                help_text="Chegirmasiz to'liq narx. Shartnoma tuzishda sukut bo'yicha olinadi",
                max_digits=12,
                verbose_name="oylik to'lov (tarif)",
            ),
        ),
    ]
