# Generated by Django 6.0.8 on 2026-10-01 16:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_class_tariff"),
        ("core", "0004_contract_requisites"),
        ("people", "0008_seed_districts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="dars raqami",
                    ),
                ),
                ("start", models.TimeField(verbose_name="boshlanishi")),
                ("end", models.TimeField(verbose_name="tugashi")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_slots",
                        to="core.branch",
                        verbose_name="filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "dars vaqti",
                "verbose_name_plural": "dars vaqtlari (qo'ng'iroqlar)",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Dushanba"),
                            (2, "Seshanba"),
                            (3, "Chorshanba"),
                            (4, "Payshanba"),
                            (5, "Juma"),
                            (6, "Shanba"),
                        ],
                        verbose_name="hafta kuni",
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="amal qila boshlagan")),
                (
                    "valid_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="amal qilgan oxirgi kun"
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to="core.academicyear",
                        verbose_name="o'quv yili",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to="core.branch",
                        verbose_name="filial",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="kiritgan",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to="academics.group",
                        verbose_name="guruh",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.room",
                        verbose_name="xona",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to="academics.subject",
                        verbose_name="fan",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to="people.teacher",
                        verbose_name="o'qituvchi",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to="academics.timeslot",
                        verbose_name="dars vaqti",
                    ),
                ),
            ],
            options={
                "verbose_name": "dars",
                "verbose_name_plural": "darslar (jadval)",
                "ordering": ["weekday", "slot__number"],
            },
        ),
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.UniqueConstraint(
                fields=("branch", "number"), name="unique_slot_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("end__gt", models.F("start"))),
                name="slot_end_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["branch", "weekday", "slot"],
                name="academics_l_branch__4d7a14_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="lesson_validity_order",
            ),
        ),
    ]
