# Generated by Django 6.0.8 on 2026-10-01 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_timetable"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupsubject",
            name="hours_per_week",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Dars jadvalidagi limit. 0 — belgilanmagan",
                validators=[django.core.validators.MaxValueValidator(20)],
                verbose_name="haftalik soat",
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="is_break",
            field=models.BooleanField(
                default=False,
                help_text="Bu vaqtga dars qo'yilmaydi",
                verbose_name="tanaffus (obed)",
            ),
        ),
    ]
