# Generated by Django 6.0.8 on 2026-10-03 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_hours_and_breaks"),
        ("people", "0011_teacher_card"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="sana")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("B", "Keldi"),
                            ("Y", "Kelmadi"),
                            ("K", "Kechikdi"),
                            ("S", "Sababli"),
                        ],
                        max_length=1,
                        verbose_name="belgi",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="izoh"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="belgilangan"),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance",
                        to="academics.schoolclass",
                        verbose_name="sinf",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_attendance",
                        to="people.student",
                        verbose_name="o'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "sinf davomati",
                "verbose_name_plural": "sinf davomati",
                "indexes": [
                    models.Index(
                        fields=["school_class", "date"],
                        name="academics_c_school__02d130_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "date"), name="one_class_mark_per_day"
                    )
                ],
            },
        ),
    ]
