# Generated by Django 6.0.8 on 2026-09-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="nomi"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="manzil"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="telefon"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="faol")),
            ],
            options={
                "verbose_name": "filial",
                "verbose_name_plural": "filiallar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "name",
                    models.CharField(
                        default="Maktab", max_length=120, verbose_name="maktab nomi"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        default="Maktab", max_length=40, verbose_name="qisqa nom"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(blank=True, max_length=160, verbose_name="shior"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="branding/", verbose_name="logo"
                    ),
                ),
                (
                    "brand_color",
                    models.CharField(
                        default="#0F766E",
                        max_length=7,
                        verbose_name="asosiy rang (HEX)",
                    ),
                ),
            ],
            options={
                "verbose_name": "maktab sozlamalari",
                "verbose_name_plural": "maktab sozlamalari",
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Masalan: 2026-2027",
                        max_length=20,
                        unique=True,
                        verbose_name="nomi",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="boshlanishi")),
                ("end_date", models.DateField(verbose_name="tugashi")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="joriy"),
                ),
            ],
            options={
                "verbose_name": "o'quv yili",
                "verbose_name_plural": "o'quv yillari",
                "ordering": ["-start_date"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("is_current",),
                        name="only_one_current_academic_year",
                    )
                ],
            },
        ),
    ]
