# Generated by Django 6.0.8 on 2026-09-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolsettings",
            name="brand_color",
            field=models.CharField(
                default="#08915E", max_length=7, verbose_name="asosiy rang (HEX)"
            ),
        ),
    ]
