# Generated by Django 6.0.8 on 2026-09-27 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_brand_color_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolsettings",
            name="brand_color",
            field=models.CharField(
                default="#08915E",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9A-Fa-f]{6}$", "Masalan: #08915E"
                    )
                ],
                verbose_name="asosiy rang (HEX)",
            ),
        ),
    ]
