# Generated by Django 6.0.8 on 2026-09-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_schoolsettings_brand_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="bank_account",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="hisob raqami (H/R)"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="bank_mfo",
            field=models.CharField(blank=True, max_length=10, verbose_name="MFO"),
        ),
        migrations.AddField(
            model_name="branch",
            name="bank_name",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="bank nomi"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="director_name",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="direktor (F.I.Sh.)"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="inn",
            field=models.CharField(
                blank=True, max_length=12, verbose_name="STIR (INN)"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="legal_name",
            field=models.CharField(
                blank=True,
                help_text="Shartnomada: masalan, «...» MCHJ",
                max_length=160,
                verbose_name="yuridik nomi",
            ),
        ),
    ]
