# Generated by Django 6.0.8 on 2026-09-29 06:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_alter_schoolsettings_brand_color"),
        ("people", "0006_student_statuses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DormRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Masalan: 1-xona bog'cha",
                        max_length=60,
                        verbose_name="nomi",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "O'g'il bolalar"),
                            ("female", "Qiz bolalar"),
                            ("mixed", "Aralash"),
                        ],
                        max_length=6,
                        verbose_name="kimlar uchun",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="o'rinlar soni",
                    ),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Yotoqxona to'lovi (grafik uchun)",
                        max_digits=12,
                        verbose_name="oylik to'lov",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="faol")),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="izoh"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dorm_rooms",
                        to="core.branch",
                        verbose_name="filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "yotoqxona xonasi",
                "verbose_name_plural": "yotoqxona xonalari",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DormStay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                ("checked_in", models.DateField(verbose_name="kirgan sana")),
                (
                    "checked_out",
                    models.DateField(
                        blank=True, null=True, verbose_name="chiqqan sana"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="izoh"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stays",
                        to="dorm.dormroom",
                        verbose_name="xona",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dorm_stays",
                        to="people.student",
                        verbose_name="o'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "yotoqxonada yashash",
                "verbose_name_plural": "yotoqxonada yashash qaydlari",
                "ordering": ["-checked_in"],
            },
        ),
        migrations.AddConstraint(
            model_name="dormroom",
            constraint=models.UniqueConstraint(
                fields=("branch", "name"), name="unique_dorm_room_name"
            ),
        ),
        migrations.AddIndex(
            model_name="dormstay",
            index=models.Index(
                fields=["room", "checked_out"], name="dorm_dormst_room_id_7f0b94_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dormstay",
            constraint=models.UniqueConstraint(
                condition=models.Q(("checked_out__isnull", True)),
                fields=("student",),
                name="one_active_dorm_stay",
            ),
        ),
        migrations.AddConstraint(
            model_name="dormstay",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("checked_out__isnull", True),
                    ("checked_out__gte", models.F("checked_in")),
                    _connector="OR",
                ),
                name="dorm_stay_dates",
            ),
        ),
    ]
