# Generated by Django 6.0.8 on 2026-09-29 06:26

import django.core.validators
from django.db import migrations, models


def is_active_to_status(apps, schema_editor):
    """Eski "faol emas" xonalar yangi holatda "Nofaol" bo'lib qolsin."""
    DormRoom = apps.get_model("dorm", "DormRoom")
    DormRoom.objects.filter(is_active=False).update(status="inactive")


def status_to_is_active(apps, schema_editor):
    DormRoom = apps.get_model("dorm", "DormRoom")
    DormRoom.objects.exclude(status="active").update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ("dorm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dormroom",
            name="floor",
            field=models.CharField(
                blank=True,
                help_text="Masalan: 1-qavat",
                max_length=30,
                verbose_name="qavat",
            ),
        ),
        migrations.AddField(
            model_name="dormroom",
            name="room_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (2, "2 o'rinli"),
                    (4, "4 o'rinli"),
                    (6, "6 o'rinli"),
                    (8, "8 o'rinli"),
                ],
                default=2,
                verbose_name="xona turi",
            ),
        ),
        migrations.AddField(
            model_name="dormroom",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Faol"),
                    ("inactive", "Nofaol"),
                    ("repair", "Ta'mirda"),
                ],
                db_index=True,
                default="active",
                max_length=8,
                verbose_name="holati",
            ),
        ),
        migrations.AlterField(
            model_name="dormroom",
            name="capacity",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="sig'im (o'rinlar)",
            ),
        ),
        migrations.AlterField(
            model_name="dormroom",
            name="gender",
            field=models.CharField(
                choices=[("male", "O'g'il"), ("female", "Qiz"), ("mixed", "Aralash")],
                max_length=6,
                verbose_name="jinsi",
            ),
        ),
        migrations.AlterField(
            model_name="dormroom",
            name="name",
            field=models.CharField(
                help_text="Masalan: 29-xona",
                max_length=60,
                verbose_name="nomi (raqami)",
            ),
        ),
        migrations.RunPython(is_active_to_status, status_to_is_active),
        migrations.RemoveField(
            model_name="dormroom",
            name="is_active",
        ),
    ]
