# Generated by Django 6.0.8 on 2026-10-02 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dorm", "0003_stay_monthly_fee"),
        ("people", "0011_teacher_card"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DormAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="sana")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("B", "Bor"),
                            ("Y", "Yo'q"),
                            ("K", "Kechikdi"),
                            ("S", "Sababli"),
                        ],
                        max_length=1,
                        verbose_name="belgi",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="belgilangan"),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance",
                        to="dorm.dormstay",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dorm_attendance",
                        to="people.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "yotoqxona davomati",
                "verbose_name_plural": "yotoqxona davomati",
                "indexes": [
                    models.Index(fields=["date"], name="dorm_dormat_date_7eb755_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "date"), name="one_dorm_mark_per_day"
                    )
                ],
            },
        ),
    ]
