# Generated by Django 6.0.8 on 2026-10-02 04:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_contract_requisites"),
        ("people", "0011_teacher_card"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "first_category_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="1-toifa ustamasi (%)",
                    ),
                ),
                (
                    "second_category_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="2-toifa ustamasi (%)",
                    ),
                ),
                (
                    "specialist_category_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Mutaxassis ustamasi (%)",
                    ),
                ),
                (
                    "highest_category_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Oliy toifa ustamasi (%)",
                    ),
                ),
                (
                    "certificate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("30"),
                        help_text="Sertifikat fanidan tushgan asosiy oylikka",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="sertifikat ustamasi (%)",
                    ),
                ),
                (
                    "language_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15"),
                        help_text="Rus / ingliz tilidagi sinflar darslaridan tushgan qismga",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="til ustamasi (%)",
                    ),
                ),
                (
                    "homeroom_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Sinf to'lov ulushiga ko'paytiriladi",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="sinf rahbarlik (so'm, oyiga)",
                    ),
                ),
                (
                    "branch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_settings",
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "oylik sozlamalari",
                "verbose_name_plural": "oylik sozlamalari",
            },
        ),
        migrations.CreateModel(
            name="Penalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "month",
                    models.DateField(help_text="Oyning 1-sanasi", verbose_name="oy"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1"))
                        ],
                        verbose_name="summa",
                    ),
                ),
                ("reason", models.CharField(max_length=255, verbose_name="sababi")),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="bekor qilingan"
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="bekor qilish sababi"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="penalties",
                        to="core.branch",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="penalties",
                        to="people.teacher",
                        verbose_name="o'qituvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "jarima",
                "verbose_name_plural": "jarimalar",
                "ordering": ["-created_at"],
            },
        ),
    ]
