# Generated by Django 6.0.8 on 2026-10-02 05:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_contract_requisites"),
        ("finance", "0004_dorm_invoices"),
        ("payroll", "0001_initial"),
        ("people", "0011_teacher_card"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payrollsettings",
            name="homeroom_amount",
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="homeroom_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("30000"),
                help_text="Har o'quvchi uchun: stavka × to'lagan / to'liq tarif",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="sinf rahbarlik (so'm, o'quvchi boshiga)",
            ),
        ),
        migrations.CreateModel(
            name="SalaryPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="yangilangan"),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="Oyning 1-sanasi", verbose_name="qaysi oy uchun"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("advance", "Avans"), ("salary", "Oylik")],
                        max_length=10,
                        verbose_name="turi",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1"))
                        ],
                        verbose_name="summa",
                    ),
                ),
                ("paid_on", models.DateField(verbose_name="berilgan sana")),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="izoh"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_payments",
                        to="core.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_payment",
                        to="finance.expense",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_payments",
                        to="people.teacher",
                        verbose_name="o'qituvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "oylik to'lovi",
                "verbose_name_plural": "oylik to'lovlari",
                "ordering": ["-paid_on", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["branch", "month"],
                        name="payroll_sal_branch__b17380_idx",
                    )
                ],
            },
        ),
    ]
